### ISSUE TITLE
Migrate to Webpack 2

### ISSUE THREAD

**Issue by BrOrlandi** [BrOrlandi/react-webpack-boilerplate#1]

**Comment by nihey** [comment]
If you don't mind, I can take this.

I've recently migrated mine to Webpack 2: https://github.com/nihey/webpack2-single-page-boilerplate

**Comment by BrOrlandi** [comment]
I have made another React-boilerplate at https://github.com/BrOrlandi/react-boilerplate
More modern, based on webpack 2 and with hot module replacement.

If you want to help, contribute to the new boilerplate.

I will set this repo as deprecated.
